filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
build:
    tests:
        override:
            -
                command: 'composer phpunit'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
